export const AI_BUBBLE_PHRASES = [
    // Dicas do App (Interações UI)
    "Clique no card de saldo para explorar estatísticas.",
    "Arraste uma movimentação para a direita para editar.",
    "Arraste uma movimentação para a esquerda para apagar.",
    "Use os filtros na Home para ver apenas receitas ou despesas.",
    "Você pode categorizar um gasto como 'Recorrente' ou 'Parcelado'.",
    "Passe os meses para a esquerda ou direita no topo da tela inicial.",
    "Acesse o seu Perfil para alterar a moeda ou idioma do Zimbroo.",
    "Ao adicionar uma transação parcelada, eu calculo o valor mensal pra você.",
    
    // Dicas da Inteligência Artificial
    "Eu consigo responder qualquer dúvida sobre suas finanças!",
    "Adicione qualquer movimentação com voz ou texto.",
    "Pergunte 'Quanto gastei com Uber esse mês?' para ver a mágica.",
    "Fale 'Comprei um café por 5 reais' e eu registro para você.",
    "Eu consigo alterar o valor de uma transação se você pedir.",
    "Peça para 'Excluir a última compra' se cometeu um erro.",
    "Basta me dizer o valor e o que comprou, eu descubro a categoria.",
    "Se você mudou de país, peça a IA: 'mude a moeda para euro'.",
    
    // Motivação
    "Pequenos hábitos, grandes resultados financeiros. 💰",
    "O segredo da riqueza é saber para onde o dinheiro está indo.",
    "Zimbroo e você: uma parceria de sucesso para o seu bolso.",
    "Dinheiro sob controle é paz de espírito. 🧘‍♂️",
    "Cada registro é um tijolinho no seu castelo financeiro.",
    "Nada de 'gastos fantasmas'! Mantenha tudo no radar. 👻",
    "A clareza financeira te dá liberdade.",
    "No mobile, toque nos filtros de 'Receitas' ou 'Despesas' para organizar sua visão.",
    "Precisa de um resumo? Pergunte 'Quanto sobrou esse mês?'.",
    "Você pode me pedir para 'Adicionar um bônus de 500 reais' como receita.",
    "Eu aprendo com você: se eu errar uma categoria, pode me corrigir.",
    "No computador, você pode ver mais detalhes de cada categoria passando o mouse.",
    "Tente dizer 'Quanto gastei no mercado semana passada?'",
    "Cada transação com IA é processada em segundos para sua comodidade.",
    "Esqueceu de anotar algo ontem? Diga 'Ontem gastei 30 reais na feira'.",
    "Lembre-se de conferir seu saldo total no Menu lateral.",
    "O Zimbroo funciona offline também para registros rápidos!",
    "Se você tiver muitas transações, use a barra de busca para encontrar rápido.",
    "Você sabia? Eu consigo calcular parcelas complexas se você me pedir.",
    "Mantenha o app instalado como PWA para receber notificações e facilitar o uso.",
    "A saúde do seu bolso começa com o registro de cada pequeno café. ☕",
    "Quer economizar? Peça 'Dê uma dica para eu gastar menos esse mês'.",
    "Eu posso te ajudar a planejar sua próxima viagem, basta perguntar!",
    "O gráfico de linhas mostra a evolução do seu patrimônio ao longo dos meses."
];
