export const AI_BUBBLE_PHRASES = [
    "Bora registrar esse cafezinho? Cada centavo conta!",
    "O segredo da riqueza é saber para onde o dinheiro está indo. 💸",
    "Já anotou as compras do mercado hoje?",
    "Um pequeno registro agora, uma grande economia no futuro.",
    "Zimbroo está pronto para organizar suas finanças. Vamos começar?",
    "Dinheiro sob controle é paz de espírito. Registre seu gasto! 🧘‍♂️",
    "Que tal dar uma olhada no seu saldo antes de sair?",
    "Anotar seus gastos leva menos de 10 segundos. Vamos lá?",
    "Você no comando do seu dinheiro. O que gastou agora?",
    "Organização é o primeiro passo para realizar seus sonhos.",
    "Não deixe para amanhã o gasto que você fez hoje!",
    "Pequenas economias geram grandes fortunas. 💰",
    "Como está sua meta de economia para este mês?",
    "Lembrete: a disciplina financeira te leva mais longe.",
    "Já pagou aquele boleto? Registra aqui para não esquecer.",
    "Sua carteira agradece quando você se organiza.",
    "O Zimbroo adora ver suas finanças em dia!",
    "Transparência total com seu suado dinheiro. Registre!",
    "Um brinde à sua saúde financeira! 🥂",
    "Evite sustos no fim do mês: anote tudo agora.",
    "Você já é um mestre das finanças, continue registrando!",
    "Nada como a sensação de ter tudo sob controle. 😌",
    "Qual foi a última aventura financeira do dia?",
    "Economizar não é sobre gastar menos, é sobre gastar melhor.",
    "Mantenha o foco nos seus objetivos financeiros.",
    "O Zimbroo é seu parceiro fiel na jornada da economia.",
    "Já viu como está seu gráfico de gastos hoje? 📊",
    "Cada registro é um tijolinho no seu castelo financeiro.",
    "Menos estresse, mais controle. Anote seu gasto!",
    "O café estava bom? Não esquece de anotar o valor! ☕",
    "Finanças em dia, mente tranquila.",
    "Você está fazendo um ótimo trabalho cuidando do seu dinheiro.",
    "Que tal conferir se sobrou algo para o lazer?",
    "A clareza financeira te dá liberdade.",
    "Seus registros estão te ajudando a economizar?",
    "Dê adeus às dúvidas: anote e confira depois!",
    "O equilíbrio financeiro começa com um simples registro.",
    "Zimbroo: seu dinheiro, suas regras, sua organização.",
    "Sabe quanto você já economizou este mês? 🌟",
    "Vamos transformar seu controle financeiro em um hábito?",
    "Um passo de cada vez até a sua independência financeira. ",
    "Registre seus ganhos também! Ver a conta crescer é ótimo. 📈",
    "Sua conta bancária está sorrindo para você hoje?",
    "Lute contra os gastos impulsivos anotando tudo aqui.",
    "O Zimbroo te ajuda a ver o quadro geral.",
    "Conhecimento é poder, especialmente sobre seu dinheiro.",
    "Onde foi parar aquela nota de 50? Anote aqui!",
    "Investir no seu controle é investir no seu futuro.",
    "Nada escapa do seu radar financeiro com o Zimbroo. 🕵️‍♂️",
    "Que tal um balanço rápido do seu dia?",
    "Sua jornada financeira é única. Vamos registrar?",
    "Mais consciência, menos desperdício.",
    "O Zimbroo facilita sua vida. Basta falar ou escrever!",
    "Você merece uma vida financeira sem preocupações.",
    "Quais são as suas prioridades para hoje?",
    "Um lembrete amigável: registre aquele lanchinho. 🍔",
    "Transforme dados em decisões inteligentes com o Zimbroo.",
    "O sucesso financeiro é a soma de pequenos esforços diários.",
    "Não subestime o poder de uma planilha (ou app) em dia!",
    "Zimbroo: inteligência para o seu bolso.",
    "Já separou o dinheiro para o investimento do mês?",
    "Economia é a arte de escolher o que é mais importante.",
    "Seu futuro 'eu' vai te agradecer por este registro.",
    "Controle sua ansiedade financeira com organização.",
    "Vamos bater sua meta de economia essa semana?",
    "O lazer fica muito melhor quando está planejado. 🏖️",
    "Evite a 'neve' de gastos pequenos que se tornam uma avalanche.",
    "Mantenha seus sonhos vivos através do controle financeiro.",
    "O Zimbroo torna a gestão do dinheiro algo prazeroso.",
    "Qual será o seu próximo grande passo financeiro?",
    "Registrar é a melhor forma de não perder dinheiro.",
    "Seja o CEO da sua vida financeira. 👔",
    "O Zimbroo simplifica o que parece complexo.",
    "Quanto você quer ter guardado no fim do ano?",
    "Disciplina é a ponte entre metas e realizações.",
    "Nada de 'gastos fantasmas'! Registre tudo. 👻",
    "O Zimbroo é o espelho da sua saúde financeira.",
    "Já anotou o transporte de hoje? 🚗",
    "Pequenos hábitos, grandes resultados financeiros.",
    "O Zimbroo te mantém informado sobre suas escolhas.",
    "Vamos dar um check nas suas despesas fixas?",
    "Seu dinheiro trabalha para você ou você trabalha para ele?",
    "A organização financeira abre portas para novas oportunidades.",
    "O Zimbroo é a ferramenta certa para quem quer crescer.",
    "Já registrou o presente que comprou? 🎁",
    "Ver seus gastos te dá controle sobre o amanhã.",
    "O equilíbrio entre ganhar, gastar e poupar.",
    "Zimbroo: onde seu dinheiro encontra a organização.",
    "O que você aprendeu com seus gastos esse mês?",
    "Seus sonhos são o combustível da sua economia.",
    "Vamos evitar as surpresas na fatura do cartão? 💳",
    "O Zimbroo te ajuda a manter os pés no chão.",
    "Ter dinheiro guardado é ter opções na vida.",
    "Qual gasto você pode reduzir sem perder qualidade de vida?",
    "O registro de hoje é a análise de amanhã.",
    "Zimbroo: seu assistente financeiro pessoal 24h.",
    "Vamos celebrar cada pequena vitória financeira! 🎉",
    "Organize-se para poder gastar com o que realmente ama.",
    "O segredo é começar. O que você registrou agora?",
    "Zimbroo e você: uma parceria de sucesso para o seu bolso."
];
